name: Test

on:
    - push
    - pull_request

jobs:
    linux-autotools:
        name: Linux Autotools
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                configureFlags:
                    - ""
                    - "--with-introspection"
                    - "--with-gegl"
                include:
                    - configureFlags: "--with-introspection"
                      extraDeps: "libgirepository1.0-dev"
                    - configureFlags: "--with-gegl"
                      extraDeps: "libgegl-dev"
        steps:
            - uses: actions/checkout@v4
            - name: "Install dependencies"
              run: |
                sudo apt-get update
                sudo apt-get install -y \
                    libjson-c-dev \
                    intltool \
                    ${{ matrix.extraDeps }}
            - name: "Build"
              run: |
                ./autogen.sh
                ./configure ${{ matrix.configureFlags }}
                make
            - name: "Run tests"
              run: make distcheck

    linux-meson:
        name: Linux Meson
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                configureFlags:
                    - ""
                    - "-Dglib=enabled -Dintrospection=enabled"
                    - "-Dgegl=enabled"
                include:
                    - configureFlags: "-Dglib=enabled -Dintrospection=enabled"
                      extraDeps: "libgirepository1.0-dev"
                    - configureFlags: "-Dgegl=enabled"
                      extraDeps: "libgegl-dev"
        steps:
            - uses: actions/checkout@v4
            - name: "Install dependencies"
              run: |
                sudo apt-get update
                sudo apt-get install -y \
                    libjson-c-dev \
                    meson \
                    ninja-build \
                    gettext \
                    ${{ matrix.extraDeps }}
            - name: "Build"
              run: |
                meson setup _build --buildtype=release -Dauto_features=disabled
                meson compile -C _build
            - name: "Run tests"
              run: meson dist -C _build
